### ISSUE TITLE
Autobuyer bids/buys unwated players + continuesly changing vales NEED FIX ASAP!!!

### ISSUE THREAD

**Issue by ab-user1** [oRastor/fut23-web-app#100]
![ab issue1](https://user-images.githubusercontent.com/72334444/194645935-3ae3627e-d383-475e-9760-996f87641e48.png)
![ab issue2](https://user-images.githubusercontent.com/72334444/194645941-708d2c48-6142-48f0-ae54-0fd9ac6bc0ba.png)

Dear Orets,

Ive been happily using your autobuyer for years and it brought me millions of coins.
However there is an issue at the moment that needs a fix asap because were losing coins like this.
When starting the autobuyer the value max bid goes into the millions for no reason, how is this possible ? i always leave this value empty
Also min bid and min buynow keeps going up, why ?
Check screenshots.
Im sure alot of people encounter this issue.
Because of this issue the autobuyer bids on unwated players like i show you in the second screenshot.
My max buy now/buy prize is set on 800 so why does the autobuyer bid 4400 on some silver player ?
I dont even want the autobuyer to bid...the autobuyer already bid on loads of silver players like this but i thought like whatever...
Now it annoys me because im losing coins like crazy and all my values are the same like all the years before.

Why if i leave max bid empty, it goes to 2.500.00+ by itself whenever i start the autobuyer
This makes no sense..

Please help!

**Comment by oRastor** [comment]
Look at #96

**Comment by ab-user1** [comment]
> Look at #96

Nope, thats not the solution.
I assume you havent checked my screenshots.
Why does the max bid change into the millions if i leave it completely empty ? this makes no sense.
The autobuyer works fine, but not like previous years.
When the max bid goes into the millions whenever i start the autobuyer, it bids on unwated players resulting in me losing lots of coins.
Cant you fix this ?

**Comment by oRastor** [comment]
I don't understand what filter condition you use and what you expect. But I see a text that you buy silver players and ASAP.

With the settings in the screenshot, it would not buy a card with a buy-now price of 4500. I use the last version for a few days.

**Comment by oRastor** [comment]
The problem can be if you switch menu tabs during auto buyer works. It's a bad idea. Before switching menu items you must stop auto buyer. Because form values randomly change. For now, I don't understand why. But I always stop auto buyer before going to another page.

**Comment by ab-user1** [comment]
> The problem can be if you switch menu tabs during auto buyer works. It's a bad idea. Before switching menu items you must stop auto buyer. Because form values randomly change. For now, I don't understand why. But I always stop auto buyer before going to another page.

LOL really bro? You think I'm that dumb?
I've been using this AUTOBUYER probably since 2015 or so and I know not to change tab while it's running.
The max bid was just going into the millions when I started the thing. It has nothing to do with me, but if you want to believe that thats fine brother.

Ive stopped using ur AUTOBUYER anyway, why?
My account already got banned after 1 week of using it just 1 hour a day.
EA is banning more now then they ever did and not 1 script or bot is safe to use now even not for a few mijs a day.

**Comment by oRastor** [comment]
Ok, I close this issue because I don't receive a description of the filtering settings.

>Ive stopped using ur AUTOBUYER anyway, why?
>My account already got banned after 1 week of using it just 1 hour a day.

Of course, maybe because you specify "wait time" too low.
