### ISSUE TITLE
Increase / decrease min bid price with every search

### ISSUE THREAD

**Issue by chrisv99** [oRastor/fut23-web-app#78]
This is not really an issue, but more a feature request.
When i'm buying items manually, I noticed that the success rate is increasing a lot when you change the minimum bid price after every search.
When i buy a 1500 coins item for example, I start with empty minimum bid and increase it to 750 (with one step of 50 coins per search) and after that back to 0. Is it possible to implement something like that? Maybe with configurable min and max values?
Thanks in advance.

**Comment by oRastor** [comment]
> start

I don't see any reason why the success rate will be increased for this case. Can you explain?

**Comment by chrisv99** [comment]
> I don't see any reason why the success rate will be increased for this case. Can you explain?

I don’t have hard evidence, but when sniping manually and doing this, I never receive duplicate players (which are already sold). My assumption is that EA is somehow caching the response for some time when you do not change the values for your search. You can try it and see what the effect is :)

**Comment by RockCity33** [comment]
I support this change request as well, it seems the search results are updated more frequently after changing the min-bid. I also think it has something to do with cache being used.  if I don't change the min-bid the webapp sometimes shows results that have already been bought.

**Comment by oRastor** [comment]
min and max bid price change every search request in the background to avoid cache problems
