### ISSUE TITLE
Having trouble installing the update

### ISSUE THREAD

**Issue by Tombomb0831** [oRastor/fut23-web-app#84]
I am not very smart with this stuff and I love the Autobuyer! When I logged in earlier today my autobuyer was gone and I have been struggling to get it back. I cant seem to get the correct install link because every time I install 1.5.3 it loads up what I attached
![Screen Shot 2021-12-17 at 3 07 46 AM](https://user-images.githubusercontent.com/96287447/146518929-44ccae93-9e73-428e-92b9-2783c34faa0d.png)
![Screen Shot 2021-12-17 at 3 07 33 AM](https://user-images.githubusercontent.com/96287447/146518934-6150b62f-2311-42e0-942e-1c8c2c9da4cc.png)

**Comment by oRastor** [comment]
I forgot to update version number in top panel

**Comment by oRastor** [comment]
updated just now

**Comment by Tombomb0831** [comment]
> updated just now

Is that the update because the “list Futbin” feature, as well with a bunch of other features, are no longer there.

**Comment by oRastor** [comment]
> > updated just now
> 
> Is that the update because the “list Futbin” feature, as well with a bunch of other features, are no longer there.

There are no any "list futbin" functionality for autobuyer in this repository. Maybe you have installed some fork or another version of autobuyer before.
