### ISSUE TITLE
Wait time not working

### ISSUE THREAD

**Issue by Kongux** [oRastor/fut23-web-app#95]
Hey oRastor, 

the wait time is not working. Bot is searching every second… the field Wait Time i filled with 3-6 seconds. I am using a .Mac. Is this the reason?
![image](https://user-images.githubusercontent.com/79310382/191674776-d634d47e-0a7d-4da4-8144-94953ab8ef58.jpg)

**Comment by oRastor** [comment]
Every year someone has this problem, what browser do you use?

**Comment by oRastor** [comment]
can you check chrome?
