### ISSUE TITLE
Issue?

### ISSUE THREAD

**Issue by ghenz187** [oRastor/fut23-web-app#97]
Yo my man big fan since Fifa 21.
I can't see the sell price after tax, it's not working. 
Also i can't see how many sold items I have or Unsold.

Is this common for this version?

**Comment by oRastor** [comment]
`I can't see the sell price after tax, it's not working.`
Where you must see it? Can you show a screenshot?

`Also i can't see how many sold items I have or Unsold.`
fixed

**Comment by ghenz187** [comment]
https://ibb.co/JFMjNzr

> `I can't see the sell price after tax, it's not working.` Where you must see it? Can you show a screenshot?
> 
> `Also i can't see how many sold items I have or Unsold.` fixed

**Comment by oRastor** [comment]
fixed, but it changes well with adjust mode

**Comment by ghenz187** [comment]
It is now automatically setting prices at max bid and min buy now even without adjust mode on? 

https://ibb.co/Cws1TQy

**Comment by oRastor** [comment]
its made to prevent using cache https://github.com/oRastor/fut23-web-app/issues/96

**Comment by ghenz187** [comment]
> its made to prevent using cache #96

Okay so it can't hurt?

**Comment by oRastor** [comment]
-

**Comment by ghenz187** [comment]
> no

thanks
