### ISSUE TITLE
Buy failed 99% of the time

### ISSUE THREAD

**Issue by SeanMcCusker** [oRastor/fut23-web-app#98]
Hi there, massive fan of this autobuyer since fut21. Noticing this year that almost everything is resulting in "buy failed". Curious if this is just me experiencing this, or a wider problem perhaps?

**Comment by bb4545** [comment]
me too

**Comment by CrispyRL94** [comment]
I have the same problem, bot only buys 20-30% of the cards, last year it was much better success rate.

**Comment by oRastor** [comment]
new logic with set min bid and min buy price every request released, please test it

**Comment by SeanMcCusker** [comment]
> new logic with set min bid and min buy price every request released, please test it

Will try now, thanks for the quick response

**Comment by SeanMcCusker** [comment]
> new logic with set min bid and min buy price every request released, please test it

Looks to be performing much better now, thanks again for getting to this so quickly

**Comment by Erenaltan2001** [comment]
I just get the error message, I have no idea why, I get maybe 1 out of 30 players.
