### ISSUE TITLE
Need New Match for English GB

### ISSUE THREAD

**Issue by darthvader666uk** [oRastor/fut23-web-app#99]
Hey!

Thank you for doing such an awesome job with this script :)

I noticed, more than likely because I'm in the UK, I needed to have the GB page as that's where it auto directs to.  Locally, I have added:

`// @match        https://www.ea.com/en-gb/fifa/ultimate-team/web-app*`

Shall I make a PR to request to add it or do you think having something like:

`// @match        https://www.ea.com/*/fifa/ultimate-team/web-app*`

So that if other people are elsewhere in the world, it will still add auto buyer?

**Comment by oRastor** [comment]
Hi, a few days ago I updated the script to add a menu item of autobuyer not by text matching. So I think it will work now for all locales.

Updated

**Comment by darthvader666uk** [comment]
> Hi, a few days ago I updated the script to add a menu item of autobuyer not by text matching. So I think it will work now for all locales.
> 
> Updated

Ah Awesome, I must have missed that! Cheers for that :)

**Comment by darthvader666uk** [comment]
Hey @oRastor !

Just tried the new update and didnt work.

it needs to be:

`// @match        https://www.ea.com/*/fifa/ultimate-team/web-app/*`

as `https://www.easports.com/*/fifa/ultimate-team/web-app/*` goes to a not found for me.

maybe ebcause im in the UK?

**Comment by darthvader666uk** [comment]
So sorry @oRastor Im being silly here.  Theres an option in tampermoney I can add my own URL's so that when it auto updates, it wont get overwritten :)

![image](https://user-images.githubusercontent.com/4082332/195812519-a13c020c-a5b6-40a2-a60e-6e3eace14f06.png)
